export const datasProjects = [
  // {
  //   title: 'Booki',
  //   description: 'Entreprise proposant un outil de planification de vacances',
  //   image: 'images/mockups/P2_Booki.jpg',
  //   linkDemo: 'https://fabien-t.github.io/Fabien_P2/',
  //   linkGit: 'https://github.com/FABIEN-T/Fabien_P2',
  //   catCard:1,
  //   bgColor: 'bg-myBlue',
  //   tagsBlue: ['HTML', 'CSS'],
  //   tagsRed: ['Responsive', 'Dev - Tools', 'Intégration de la maquette'],
  //   offsetY: 0,
  // },
  {
    title: 'Ohmyfood',
    description: 'Création d’un site de commande de repas en ligne',
    image: 'images/mockups/P3_Ohmyfood.jpg',
    linkDemo: 'https://fabien-t.github.io/FabienVarlet_3_03122021/public/',
    linkGit: 'https://github.com/FABIEN-T/FabienVarlet_3_03122021',
    catCard: 1,
    // bgColor: 'bg-gradient-to-t from-rose-900 to-myBlue',
    bgColor: 'bg-gradient-to-tl from-rose-900 to-myBlue',
    tagsBlue: ['HTML', 'Sass'],
    tagsRed: [
      'Animations CSS',
      'Loader',
      'Intégration des maquettes',
      'Mobile first',
    ],
    offsetY: 20,
  },
  {
    title: 'GameOn',
    description:
      'Landing page pour une entreprise spécialisée dans les conférences et les concours de jeux',
    image: 'images/mockups/P4_Gameon.jpg',
    linkDemo: 'https://fabien-t.github.io/GameOn-website-FR/starterOnly/',
    linkGit: 'https://github.com/FABIEN-T/GameOn-website-FR',
    catCard: 1,
    // bgColor: 'bg-myBlue',
    bgColor: 'bg-gradient-to-bl from-rose-900 to-myBlue',
    tagsBlue: ['HTML', 'CSS', 'Javascript'],
    tagsRed: ['Modale', 'Formulaire', 'Validation des champs'],
    offsetY: 40,
  },
  {
    title: 'Fisheye',
    description: 'Site de photographes freelances',
    image: 'images/mockups/P6_Fisheye.jpg',
    linkDemo: 'https://fabien-t.github.io/Front-End-Fisheye/public/index.html',
    linkGit: 'https://github.com/FABIEN-T/Front-End-Fisheye',
    catCard: 1,
    // bgColor: 'bg-myBlue',
    bgColor: 'bg-gradient-to-tl from-rose-900 to-myBlue',
    tagsBlue: ['HTML', 'Javascript', 'Sass'],
    tagsRed: [
      'Intégration de la maquette Figma',
      'Accessibilité',
      'Navigation du site avec le clavier',
      'Factory Pattern',
      'Site dyanmique',
      'Json',
      'Eslint',
    ],
    offsetY: 0,
  },
  {
    title: 'Les petits plats',
    description:
      'Développement d’un algorithme de recherche pour un site recettes de cuisine',
    image: 'images/mockups/P7_Les-petits-plats.jpg',
    linkDemo: 'https://fabien-t.github.io/Les-petits-plats/public/',
    linkGit: 'https://github.com/FABIEN-T/Front-End-Fisheye',
    catCard: 1,
    // bgColor: 'bg-myBlue',
    bgColor: 'bg-gradient-to-tl from-rose-900 to-myBlue',
    tagsBlue: ['HTML', 'Sass', 'Javascript'],
    tagsRed: [
      'Intégration de la maquette Figma',
      'Optimisation du moteur de recherche',
      'Recherche avancée par mots clés',
      'Test de deux implémentations différentes',
      'Fiche d’investigation et de  fonctionnalité',
    ],
    offsetY: 20,
  },
  {
    title: 'Billed',
    description:
      'Débogage et test d’une Solution SaaS destinées aux équipes de ressources humaines',
    image: 'images/mockups/P9_Billed.jpg',
    linkDemo: '',
    linkGit: 'https://github.com/FABIEN-T/Kasa_FV',
    catCard: 2,
    // bgColor: 'bg-myBlue',
    bgColor: 'bg-gradient-to-tl from-rose-900 to-myBlue',
    tagsBlue: ['Jest'],
    tagsRed: [
      'Débogage des parcours administrateur et employé avec Chrome debugger',
      'Tests unitaires et d’intégration sur le parcours employé',
      'Rédaction du plan de test End-to-End',
    ],
    offsetY: 40,
  },
  {
    title: 'Learn@Home',
    description: 'Définition des besoins pour une app de soutien scolaire',
    image: 'images/mockups/P10_LearnHome.jpg',
    linkDemo:
      'https://www.figma.com/file/Awk1gYG7RVguSbjv7wejqQ/P10_Fabien-VARLET_Maquettes-Learn%40Home?type=design&node-id=1-3&mode=design',
    linkGit: '',
    catCard: 3,
    // bgColor: 'bg-myBlue',
    bgColor: 'bg-gradient-to-tl from-rose-900 to-myBlue',
    tagsBlue: [],
    tagsRed: [
      'Synthèse des attentes',
      'Création des maquettes sur Figma',
      'Diagrammes de cas d’usages',
      'User Stories',
      'Tableau Kanban',
    ],
    offsetY: 40,
  },
  {
    title: 'Kasa',
    description:
      'Refonte totale en React du site de location d’appartements entre particuliers',
    image: 'images/mockups/P11_Kasa.jpg',
    linkDemo: 'https://kasa-fv.vercel.app/',
    linkGit: 'https://github.com/FABIEN-T/Kasa_FV',
    catCard: 1,
    // bgColor: 'bg-myBlue',
    bgColor: 'bg-gradient-to-tl from-rose-900 to-myBlue',
    tagsBlue: ['HTML', 'Sass', 'REACT', 'React Router'],
    tagsRed: [
      'Code legacy',
      'Intégration de la maquette Figma',
      'Responsive',
      'Json',
      'Initialisation du projet avec CRA',
    ],
    offsetY: 0,
  },
  {
    title: 'SportSee',
    description:
      'Nouvelle version du tableau de bord analytique permettant à l’utilisateur de suivre ses progrès quotidiens (poids, etc...)',
    image: 'images/mockups/P12_SportSee.jpg',
    linkDemo: '',
    linkGit: 'https://github.com/FABIEN-T/P12_SportSee',
    catCard: 2,
    // bgColor: 'bg-myBlue',
    bgColor: 'bg-gradient-to-tl from-rose-900 to-myBlue',
    tagsBlue: ['HTML', 'Sass', 'REACT', 'React Router', 'Recharts'],
    tagsRed: [
      'Récupéreration des données depuis une API sous Node.js et formatage',
      'Création et affichage des graphiques depuis les données avec la librairie Recharts',
      'Json',
      'Production d’une Documentation technique avec JsDoc',
      'Initialisation du projet avec CRA',
    ],
    offsetY: 20,
  },
  {
    title: 'Argent Bank',
    description:
      'Création du nouveau système d’authentification pour une application web bancaire',
    image: 'images/mockups/P13_Argent-Bank.jpg',
    linkDemo: '',
    linkGit: 'https://github.com/FABIEN-T/P13_Argent-Bank_Front',
    catCard: 2,
    // bgColor: 'bg-myBlue',
    bgColor: 'bg-gradient-to-tl from-rose-900 to-myBlue',
    tagsBlue: [
      'HTML',
      'CSS',
      'REACT',
      'Redux',
      'Redux Toolkit',
      'React-hook-form',
      'Axios',
    ],
    tagsRed: [
      'Implémentation d’un gestionnaire d’état / Redux, Redux Toolkit',
      'Système d’authentification, interaction avec une API',
      'Json',
      'Backend Node.js',
      'MongoDb',
      'Fichier swagger',
      'Initialisation du projet avec CRA',
    ],
    offsetY: 40,
  },
  {
    title: 'HR-net',
    description:
      'Conversion en React d’une  solution SaaS de gestion des employés utilisant jQuery',
    image: 'images/mockups/P14_HRnet.jpg',
    linkDemo: 'https://p14-h-rnet-ruddy.vercel.app/',
    linkGit: 'https://github.com/FABIEN-T/P14_HRnet',
    catCard: 1,
    // bgColor: 'bg-myBlue',
    bgColor: 'bg-gradient-to-tl from-rose-900 to-myBlue',
    tagsBlue: ['HTML', 'Styled-Components', 'REACT'],
    tagsRed: [
      'Refonte de l’application pour réduire la dette technique',
      'Analyse de la performance de l’application et déploiement',
      'Publication d’un Package Npm : modale',
      'Atomic-Design',
      'Initialisation du projet avec Vite',
    ],
    offsetY: 0,
  },
  {
    title: 'Portfolio',
    description: 'Mon portfolio utilisant le framework Tailwind CSS',
    image: 'images/mockups/Portfolio.jpg',
    linkDemo: 'https://portfolio-f-varlet.vercel.app/',
    linkGit: 'https://github.com/FABIEN-T/Portfolio_F-Varlet',
    catCard: 1,
    // bgColor: 'bg-myBlue',
    bgColor: 'bg-gradient-to-tl from-rose-900 to-myBlue',
    tagsBlue: ['HTML', 'Tailwind CSS', 'REACT'],
    tagsRed: [],
    offsetY: 40,
  },
  {
    title: 'Poterie des Tappes',
    description: 'Catalogue des artistes Christine Humann et Nelly Martinelli',
    image: 'images/mockups/Poterie.jpg',
    linkDemo: '',
    linkGit: '',
    catCard: 4,
    bgColor: 'bg-rose-800',
    tagsBlue: ['HTML', 'Sass', 'REACT'],
    tagsRed: ['Responsive', 'Json'],
    offsetY: 40,
  },
  {
    title: 'Stud & Yo',
    description:
      'Site de présentation du groupe pour démarcher les programmateurs',
    image: 'images/mockups/Stud.jpg',
    catCard: 4,
    linkDemo: '',
    linkGit: '',
    bgColor: 'bg-rose-800',
    tagsBlue: ['HTML', 'Sass', 'REACT'],
    tagsRed: ['Responsive', 'Json'],
    offsetY: 0,
  },
]
